services:
 php:
    build: ./docker/php
    container_name: fitbooking_php
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - .env
      
 mysql:
      image: mysql:5.7
      container_name: fitbooking_mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: fitbooking
        MYSQL_USER: fituser
        MYSQL_PASSWORD: fitpass
      restart: always
      command: 
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
        - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: